### ISSUE TITLE
feat: enable "merge" mode that doesn't clobber env

### ISSUE THREAD

**Issue by OliverNChalk** [memester-xyz/solenv#3]
## Details

I've implemented a merge mode for my own usage (https://github.com/proximacapital/solenv/commit/f34a3ae44415ee07ee9dc12490a35e6f9821020b), wanted to share and gauge appetite for up-streaming this.

Note that because of the way foundry handles state, the `setUp` test is kinda bunk (both tests will race each other to set state). You end up with non-deterministic test running. As a temp workaround I can refactor the tests to run all in a single file - will do this if we are keen to upstream "merge" mode.

**Comment by devanoneth** [comment]
Resolved in #7
